#!/bin/sh
# Usage: stripPicture fullname mime exportPicture

fullname="$1"
mime="$2"
exportPicture="$3"

# thumbnail options by mime type
case "$mime" in

      model/stl)
      echo  "import (\"$fullname\");" > $exportPicture.scad
      openscad --viewall --imgsize=256,256 -o $exportPicture.png $exportPicture.scad
      mv $exportPicture.png $exportPicture
      rm $exportPicture.scad
      exit
      ;;

      application/sla)
      echo  "import (\"$fullname\");" > $exportPicture.scad
      openscad --viewall --imgsize=256,256 -o $exportPicture.png $exportPicture.scad
      mv $exportPicture.png $exportPicture
      rm $exportPicture.scad
      exit
      ;;

      *)
#     case trap
      exit

esac
